index:
    path: /
    controller: App\Controller\DefaultController::index

logout:
    path: /logout
# app_lucky_number:
#     path: /lucky/number
#     controller: App\Controller\LuckyController::number
